apiVersion: v1
kind: Service
metadata:
  name: {{ include "pii-proxy.fullname" . }}
  labels:
    {{- include "pii-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pii-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.envoy.listenPort }}
    {{- if .Values.tls.enabled }}
    - name: https
      protocol: TCP
      port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.envoy.httpsPort }}
    {{- end }}
